### ISSUE TITLE
both user-define and library types are predicted

### ISSUE THREAD

**Issue by unclebob7** [MrVPlusOne/LambdaNet#7]
![image](https://user-images.githubusercontent.com/29818505/190359702-53af00cb-1bc6-46a6-9bd3-22829a60684b.png)
![image](https://user-images.githubusercontent.com/29818505/190359747-79a2c333-8fef-46ee-893e-2e99bd3db406.png)
Hi,

I am using only the *predicts user defined type checkpoint*, wonder why both user defined and library types are both predicted in a test file as shown in the images.

Thanks.

**Comment by MrVPlusOne** [comment]
Hi,

We don't currently have a model that only predicts user-defined types. The available model predicts both kinds of types as you mentioned. May I ask why do you want a model that only predicts user-defined types?

Thanks
